name: kzm
description: "KZM - AI Text Formatter powered by Google Gemini."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  google_generative_ai: ^0.4.6
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  clipboard: ^0.1.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
